---
kind: pipeline
name: node12

steps:
  - name: install
    image: &image node:12-alpine
    commands:
      - apk --no-cache add openzwave openzwave-dev build-base git curl python3
      - yarn install

  - name: typecheck
    image: *image
    commands: [yarn code:typecheck]
    depends_on: [install]

  - name: lint
    image: *image
    commands: [yarn code:lint]
    depends_on: [install]

  - name: test
    image: *image
    commands: [yarn test --color]
    depends_on: [install]
    environment:
      DEVICE_PATH: ./ttyVACM0

  - name: build
    image: *image
    commands: [yarn build]
    depends_on: [test]

---
kind: signature
hmac: aba187ab778b7d5fed83c1aa0892fce3fd163f0b42fa93f7e49aa63f5c7db73c
