arrowParens: avoid
bracketSpacing: true
printWidth: 120
quoteProps: consistent
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
overrides:
  - files:
      - '**/*.ts'
      - '**/*.js'
    options:
      tabWidth: 4
      useTabs: true
